default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: AzureAppService_development
  host: db
  username: postgres
  password: password

test:
  <<: *default
  database: AzureAppService_test
  host: db
  username: postgres
  password: password


production:
  <<: *default
  database: AzureAppService_production
  host:
  username:
  password:
