version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: bin/setup
    ports:
      - '3000:3000'
    volumes:
      -  'bundle-volume:/usr/src/app/vendor/bundle'
      - '.:/usr/src/app'
    depends_on:
      - db
  
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - 'db-volume:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

volumes:
  bundle-volume:
  db-volume:
    
    