FROM ruby:3.1.2

ENV RAILS_ENV=development 
ENV EDITOR=vim

RUN apt-get update && \
    apt-get install -y vim nodejs npm

RUN npm install --global yarn

RUN mkdir -p /usr/src/app/

WORKDIR /usr/src/app/

COPY ../Gemfile /usr/src/app/Gemfile

COPY ../Gemfile.lock /usr/src/app/Gemfile.lock

RUN bundle install --path vendor/bundle

COPY . /usr/src/app/


