name: CI/CD pipeline 
on:
  push:
    branches:
      - "**"
      - "!main"
  pull_request:
    branches:
      - main
      - stage
    types:
      - "closed"


jobs:
  docker-build:
    
  

    

    